### ISSUE TITLE
Error: Process Execution Timed out

### ISSUE THREAD

**Issue by ChrisJefferson** [steelbrain/atom-linter#130]
While editing tex files, I would see the error:

```
Error: Process execution timed out
    at /Users/caj/.atom/packages/linter-javac/node_modules/atom-linter/lib/helpers.js:79:18
```

I tried uninstalling that, now I get the same error from `linter-clang`, still while I am in a project with no java, c or c++ files!

I'm not sure what's going on. I think it happens when I run latex, which causes a number of files to quickly appear and then be deleted.

**Comment by steelbrain** [comment]
I think it's because `linter-clang`'s spawned processes take a lot of time, you could either increase the timeout (have a look at sb-exec's README about it) or try to make it work faster

**Comment by ChrisJefferson** [comment]
But (stupid question I know) why are both linter-javac and linter-clang both spawning processes when my project directory contains no Java, C or C++ files (only .tex / .pdf)

**Comment by Arcanemagus** [comment]
If you look that is coming from the `atom-linter` module. As almost all `linter-___` packages use that module Atom is simply picking one of the installed copies at random. You need to figure out which linter you have installed that is running on .tex files to determine what is taking longer than 10 seconds to run.

File an issue on whatever linter plugin that turns out to be so we can diagnose it further.

**Comment by ChrisJefferson** [comment]
Ah, thanks! Then I'm sure it's the latex one, probably hanging as my latex has horrible errors in it I imagine. I didn't understand that's how apm/npm/node worked.

**Comment by Arcanemagus** [comment]
Oh that's just something that was implemented in the `atom-linter` module to try to work around terrible linters that leave processes running _forever_. As these aren't being run from an interactive shell it's unlikely the user would notice either except in rare cases, so that timeout was added to try to catch those cases and fix them.
