### ISSUE TITLE
Make rangeFromLineNumber highlight the whole line if no column is provided

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/atom-linter#137]
Occasionally it would still be desirable to highlight the entire rest of the line, even if a word can be determined (see https://github.com/AtomLinter/linter-pyflakes/pull/38#issuecomment-228419569).

Add a flag to `rangeFromLineNumber` making it behave as it did in the previous version.

**Comment by Arcanemagus** [comment]
Hmmm, it might even be a good idea to use this behavior if no column is specified. Otherwise we could be highlighting a word that has little relation to what caused the error, other than being on the same line.

I would say that being less specific, but accurate is better than being _too_ specific, and wrong. For example in [this file](https://github.com/AtomLinter/linter-haml/blob/v1.2.1/spec/fixtures/cawsv.rb) the `tag` is highlighted, but the error is talking about `class:`. The linter only provides a line in its messages.

**Comment by steelbrain** [comment]
It's just wrong from a UX perspective to highlight an entire line, and show a tooltip whenever a user clicks anywhere in that line. As a user of linter-eslint myself, my heart beat used to go up because it used to highlight the entire text, and smart IDEs like PhpStorm only highlight the first char if the entire line is full of whitespaces to indicate that because they know that it gets the point across

**Comment by Arcanemagus** [comment]
Right now though we are highlighting ranges that are _entirely wrong_ in some cases, so something needs to be done to fix it. If you don't want to go back to the old behavior of the entire line, what do you propose?

**Comment by steelbrain** [comment]
From discussion with @Arcanemagus, we both agree that we would bump a major version and make linter only highlight characters if `column` is provided in `rangeFromLineNumber`
