### ISSUE TITLE
Error: spawn crystal ENOENT

### ISSUE THREAD

**Issue by Sija** [steelbrain/atom-linter#143]
It happens with latest [atom-crystal](https://github.com/atom-crystal/atom-crystal) on OS X El Capitan.
```
'crystal' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.
```

Crystal executable *is* in my `$PATH`, installed via _homebrew_.
```
~ ❯ which crystal
/usr/local/bin/crystal
```

Seems connected to https://github.com/steelbrain/linter/issues/726.

**Comment by steelbrain** [comment]
OSX eh, it has a PATH issue that we work around, it only works for the popular shells though. Which one do you use?

**Comment by Sija** [comment]
Yap, OSX indeed. I use ZSH.

**Comment by steelbrain** [comment]
So the PATH detection is failing, can you open the dev console (View -> Developer Tools -> Console) and execute this and send a screenshot of what you get (also make sure to black out anything sensitive)?

```js
const os = require('os')
console.log(require(os.homedir() + '/.atom/packages/linter-crystal/node_modules/consistent-env')().PATH)
```

**Comment by Sija** [comment]
![image](https://cloud.githubusercontent.com/assets/988/17486615/c65508f0-5d91-11e6-8462-ebdea7f620f5.png)

**Comment by steelbrain** [comment]
Aaha! `linter-crystal` doesn't use `atom-linter` anymore as of https://github.com/atom-crystal/linter-crystal/commit/3b132e7e66ae57e3d1fccd8bedb373e089964378 (otherwise you won't be getting this error as we work it around)

You could ping the author and ask them to use this module so you can use it on your Mac without doing some PATH vodoo magic 😄
